channels:
  - conda-forge
dependencies:
  - python==3.9
  - pip:
    - nbsphinx
    - jupyter-sphinx
    - sphinx_rtd_theme
    - tqdm
    - corner
    - periodictable
    - pandoc
    - scipy
    - numpy
    - sphinx
    - pandas
    - numpydoc
    - h5py
    - nbconvert
    - ipywidgets
    - setuptools
    - cython
    - jupyter
    - matplotlib
    - pytest
    - xlrd
