name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: build wheels
        uses: pypa/cibuildwheel@v2.12.1
        env:
          CIBW_TEST_COMMAND: pytest --pyargs refnx.reflect.test.test_reflect
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET="10.13"

      - uses: actions/upload-artifact@v3
        with:
          name: refnx-wheels
          path: ./wheelhouse/*.whl
